---

---
title: "Day2 Section"
format: html
editor: visual
---

## Derivatives in R

# Finding derivatives using R.

# f.

```{r}
# Find the slope of f(x) = x^2 at x = 3
fx <- expression(x^2)

ddf_dx <- D(expr = fx, name = "x")
ddf_dx

x <- 3
eval(ddf_dx)
```

# g.

```{r}
# Find the slope of P(a) = 2(3a + 2)^4 - 5 at a = 1.2
Pa <- expression(2 * (3 * a + 2)^4 - 5)
Slope_Pa <- D(expr = Pa, name = "a")
Slope_Pa
```

## Making another penguin plot

```{r}
# Penguin bill length vs. bill depth
library(tidyverse)
library(palmerpenguins)
head(penguins)
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point(aes(color = species)) +
  scale_color_manual(values = c("coral", "green","purple")) +
  labs( x = "Bill Length (mm)",
        y = "Bill Depth (mm)",
        title = "Penguin Bill length vs. Penguin Bill depth",
        subtitle = "Palmer Archipelago, Antarctice (2007 - 2009)",
       caption = "Collected by Dr. Kristen Gorman and colleagues at Palmer Station LTER") +
  facet_wrap(~island) +
  theme_minimal()
  
```

```{r}
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
  geom_jitter(aes(color = species)) +
  scale_color_manual(values = c("coral", "green","purple")) +
 labs( x = "Species",
        y = "Flipper Length (mm)",
        title = "Penguin Bill length vs. Penguin Bill depth",
        subtitle = "Palmer Archipelago, Antarctice (2007 - 2009)",
       caption = "Collected by Dr. Kristen Gorman and colleagues at Palmer Station LTER") +
  facet_wrap(~island) +
  theme_minimal()
  

```
